import brazilianMunicipalities from '@/data/brazilianMunicipalities.json';

const LEGACY_BRAZILIAN_STATES_AND_CITIES = [
  { value: 'AC', label: 'Acre', cities: [
    {value: 'Acrelândia', label: 'Acrelândia'}, {value: 'Assis Brasil', label: 'Assis Brasil'}, {value: 'Brasiléia', label: 'Brasiléia'}, {value: 'Bujari', label: 'Bujari'}, {value: 'Capixaba', label: 'Capixaba'},
    {value: 'Cruzeiro do Sul', label: 'Cruzeiro do Sul'}, {value: 'Epitaciolândia', label: 'Epitaciolândia'}, {value: 'Feijó', label: 'Feijó'}, {value: 'Jordão', label: 'Jordão'}, {value: 'Mâncio Lima', label: 'Mâncio Lima'},
    {value: 'Manoel Urbano', label: 'Manoel Urbano'}, {value: 'Marechal Thaumaturgo', label: 'Marechal Thaumaturgo'}, {value: 'Plácido de Castro', label: 'Plácido de Castro'}, {value: 'Porto Acre', label: 'Porto Acre'},
    {value: 'Porto Walter', label: 'Porto Walter'}, {value: 'Rio Branco', label: 'Rio Branco'}, {value: 'Rodrigues Alves', label: 'Rodrigues Alves'}, {value: 'Santa Rosa do Purus', label: 'Santa Rosa do Purus'},
    {value: 'Sena Madureira', label: 'Sena Madureira'}, {value: 'Senador Guiomard', label: 'Senador Guiomard'}, {value: 'Tarauacá', label: 'Tarauacá'}, {value: 'Xapuri', label: 'Xapuri'}
  ]},
  { value: 'AL', label: 'Alagoas', cities: [
    {value: 'Água Branca', label: 'Água Branca'}, {value: 'Anadia', label: 'Anadia'}, {value: 'Arapiraca', label: 'Arapiraca'}, {value: 'Atalaia', label: 'Atalaia'}, {value: 'Barra de Santo Antônio', label: 'Barra de Santo Antônio'},
    {value: 'Barra de São Miguel', label: 'Barra de São Miguel'}, {value: 'Batalha', label: 'Batalha'}, {value: 'Belém', label: 'Belém'}, {value: 'Belo Monte', label: 'Belo Monte'}, {value: 'Boca da Mata', label: 'Boca da Mata'},
    {value: 'Branquinha', label: 'Branquinha'}, {value: 'Cacimbinhas', label: 'Cacimbinhas'}, {value: 'Cajueiro', label: 'Cajueiro'}, {value: 'Campestre', label: 'Campestre'}, {value: 'Campo Alegre', label: 'Campo Alegre'},
    {value: 'Campo Grande', label: 'Campo Grande'}, {value: 'Canapi', label: 'Canapi'}, {value: 'Capela', label: 'Capela'}, {value: 'Carneiros', label: 'Carneiros'}, {value: 'Chã Preta', label: 'Chã Preta'},
    {value: 'Coité do Nóia', label: 'Coité do Nóia'}, {value: 'Colônia Leopoldina', label: 'Colônia Leopoldina'}, {value: 'Coqueiro Seco', label: 'Coqueiro Seco'}, {value: 'Coruripe', label: 'Coruripe'}, {value: 'Craíbas', label: 'Craíbas'},
    {value: 'Delmiro Gouveia', label: 'Delmiro Gouveia'}, {value: 'Dois Riachos', label: 'Dois Riachos'}, {value: 'Estrela de Alagoas', label: 'Estrela de Alagoas'}, {value: 'Feira Grande', label: 'Feira Grande'}, {value: 'Feliz Deserto', label: 'Feliz Deserto'},
    {value: 'Flexeiras', label: 'Flexeiras'}, {value: 'Girau do Ponciano', label: 'Girau do Ponciano'}, {value: 'Ibateguara', label: 'Ibateguara'}, {value: 'Igaci', label: 'Igaci'}, {value: 'Igreja Nova', label: 'Igreja Nova'},
    {value: 'Inhapi', label: 'Inhapi'}, {value: 'Jacaré dos Homens', label: 'Jacaré dos Homens'}, {value: 'Jacuípe', label: 'Jacuípe'}, {value: 'Japaratinga', label: 'Japaratinga'}, {value: 'Jaramataia', label: 'Jaramataia'},
    {value: 'Jequiá da Praia', label: 'Jequiá da Praia'}, {value: 'Joaquim Gomes', label: 'Joaquim Gomes'}, {value: 'Jundiá', label: 'Jundiá'}, {value: 'Junqueiro', label: 'Junqueiro'}, {value: 'Lagoa da Canoa', label: 'Lagoa da Canoa'},
    {value: 'Limoeiro de Anadia', label: 'Limoeiro de Anadia'}, {value: 'Maceió', label: 'Maceió'}, {value: 'Major Isidoro', label: 'Major Isidoro'}, {value: 'Mar Vermelho', label: 'Mar Vermelho'}, {value: 'Maragogi', label: 'Maragogi'},
    {value: 'Maravilha', label: 'Maravilha'}, {value: 'Marechal Deodoro', label: 'Marechal Deodoro'}, {value: 'Maribondo', label: 'Maribondo'}, {value: 'Mata Grande', label: 'Mata Grande'}, {value: 'Matriz de Camaragibe', label: 'Matriz de Camaragibe'},
    {value: 'Messias', label: 'Messias'}, {value: 'Minador do Negrão', label: 'Minador do Negrão'}, {value: 'Monteirópolis', label: 'Monteirópolis'}, {value: 'Murici', label: 'Murici'}, {value: 'Novo Lino', label: 'Novo Lino'},
    {value: 'Olho d\'Água das Flores', label: 'Olho d\'Água das Flores'}, {value: 'Olho d\'Água do Casado', label: 'Olho d\'Água do Casado'}, {value: 'Olho d\'Água Grande', label: 'Olho d\'Água Grande'}, {value: 'Olivença', label: 'Olivença'}, {value: 'Ouro Branco', label: 'Ouro Branco'},
    {value: 'Palestina', label: 'Palestina'}, {value: 'Palmeira dos Índios', label: 'Palmeira dos Índios'}, {value: 'Pão de Açúcar', label: 'Pão de Açúcar'}, {value: 'Pariconha', label: 'Pariconha'}, {value: 'Paripueira', label: 'Paripueira'},
    {value: 'Passo de Camaragibe', label: 'Passo de Camaragibe'}, {value: 'Paulo Jacinto', label: 'Paulo Jacinto'}, {value: 'Penedo', label: 'Penedo'}, {value: 'Piaçabuçu', label: 'Piaçabuçu'}, {value: 'Pilar', label: 'Pilar'},
    {value: 'Pindoba', label: 'Pindoba'}, {value: 'Piranhas', label: 'Piranhas'}, {value: 'Poço das Trincheiras', label: 'Poço das Trincheiras'}, {value: 'Porto Calvo', label: 'Porto Calvo'}, {value: 'Porto de Pedras', label: 'Porto de Pedras'},
    {value: 'Porto Real do Colégio', label: 'Porto Real do Colégio'}, {value: 'Quebrangulo', label: 'Quebrangulo'}, {value: 'Rio Largo', label: 'Rio Largo'}, {value: 'Roteiro', label: 'Roteiro'}, {value: 'Santa Luzia do Norte', label: 'Santa Luzia do Norte'},
    {value: 'Santana do Ipanema', label: 'Santana do Ipanema'}, {value: 'Santana do Mundaú', label: 'Santana do Mundaú'}, {value: 'São Brás', label: 'São Brás'}, {value: 'São José da Laje', label: 'São José da Laje'}, {value: 'São José da Tapera', label: 'São José da Tapera'},
    {value: 'São Luís do Quitunde', label: 'São Luís do Quitunde'}, {value: 'São Miguel dos Campos', label: 'São Miguel dos Campos'}, {value: 'São Miguel dos Milagres', label: 'São Miguel dos Milagres'}, {value: 'São Sebastião', label: 'São Sebastião'}, {value: 'Satuba', label: 'Satuba'},
    {value: 'Senador Rui Palmeira', label: 'Senador Rui Palmeira'}, {value: 'Tanque d\'Arca', label: 'Tanque d\'Arca'}, {value: 'Taquarana', label: 'Taquarana'}, {value: 'Teotônio Vilela', label: 'Teotônio Vilela'}, {value: 'Traipu', label: 'Traipu'},
    {value: 'União dos Palmares', label: 'União dos Palmares'}, {value: 'Viçosa', label: 'Viçosa'}
  ]},
  { value: 'AM', label: 'Amazonas', cities: [
    {value: 'Alvarães', label: 'Alvarães'}, {value: 'Amaturá', label: 'Amaturá'}, {value: 'Anamã', label: 'Anamã'}, {value: 'Anori', label: 'Anori'}, {value: 'Apuí', label: 'Apuí'},
    {value: 'Atalaia do Norte', label: 'Atalaia do Norte'}, {value: 'Autazes', label: 'Autazes'}, {value: 'Barcelos', label: 'Barcelos'}, {value: 'Barreirinha', label: 'Barreirinha'}, {value: 'Benjamin Constant', label: 'Benjamin Constant'},
    {value: 'Beruri', label: 'Beruri'}, {value: 'Boa Vista do Ramos', label: 'Boa Vista do Ramos'}, {value: 'Boca do Acre', label: 'Boca do Acre'}, {value: 'Borba', label: 'Borba'}, {value: 'Caapiranga', label: 'Caapiranga'},
    {value: 'Canutama', label: 'Canutama'}, {value: 'Carauari', label: 'Carauari'}, {value: 'Careiro', label: 'Careiro'}, {value: 'Careiro da Várzea', label: 'Careiro da Várzea'}, {value: 'Coari', label: 'Coari'},
    {value: 'Codajás', label: 'Codajás'}, {value: 'Eirunepé', label: 'Eirunepé'}, {value: 'Envira', label: 'Envira'}, {value: 'Fonte Boa', label: 'Fonte Boa'}, {value: 'Guajará', label: 'Guajará'},
    {value: 'Humaitá', label: 'Humaitá'}, {value: 'Ipixuna', label: 'Ipixuna'}, {value: 'Iranduba', label: 'Iranduba'}, {value: 'Itacoatiara', label: 'Itacoatiara'}, {value: 'Itamarati', label: 'Itamarati'},
    {value: 'Itapiranga', label: 'Itapiranga'}, {value: 'Japurá', label: 'Japurá'}, {value: 'Juruá', label: 'Juruá'}, {value: 'Jutaí', label: 'Jutaí'}, {value: 'Lábrea', label: 'Lábrea'},
    {value: 'Manacapuru', label: 'Manacapuru'}, {value: 'Manaquiri', label: 'Manaquiri'}, {value: 'Manaus', label: 'Manaus'}, {value: 'Manicoré', label: 'Manicoré'}, {value: 'Maraã', label: 'Maraã'},
    {value: 'Maués', label: 'Maués'}, {value: 'Nhamundá', label: 'Nhamundá'}, {value: 'Nova Olinda do Norte', label: 'Nova Olinda do Norte'}, {value: 'Novo Airão', label: 'Novo Airão'}, {value: 'Novo Aripuanã', label: 'Novo Aripuanã'},
    {value: 'Parintins', label: 'Parintins'}, {value: 'Pauini', label: 'Pauini'}, {value: 'Presidente Figueiredo', label: 'Presidente Figueiredo'}, {value: 'Rio Preto da Eva', label: 'Rio Preto da Eva'}, {value: 'Santa Isabel do Rio Negro', label: 'Santa Isabel do Rio Negro'},
    {value: 'Santo Antônio do Içá', label: 'Santo Antônio do Içá'}, {value: 'São Gabriel da Cachoeira', label: 'São Gabriel da Cachoeira'}, {value: 'São Paulo de Olivença', label: 'São Paulo de Olivença'}, {value: 'São Sebastião do Uatumã', label: 'São Sebastião do Uatumã'}, {value: 'Silves', label: 'Silves'},
    {value: 'Tabatinga', label: 'Tabatinga'}, {value: 'Tapauá', label: 'Tapauá'}, {value: 'Tefé', label: 'Tefé'}, {value: 'Tonantins', label: 'Tonantins'}, {value: 'Uarini', label: 'Uarini'},
    {value: 'Urucará', label: 'Urucará'}, {value: 'Urucurituba', label: 'Urucurituba'}
  ]},
  { value: 'AP', label: 'Amapá', cities: [
    {value: 'Amapá', label: 'Amapá'}, {value: 'Calçoene', label: 'Calçoene'}, {value: 'Cutias', label: 'Cutias'}, {value: 'Ferreira Gomes', label: 'Ferreira Gomes'}, {value: 'Itaubal', label: 'Itaubal'},
    {value: 'Laranjal do Jari', label: 'Laranjal do Jari'}, {value: 'Macapá', label: 'Macapá'}, {value: 'Mazagão', label: 'Mazagão'}, {value: 'Oiapoque', label: 'Oiapoque'}, {value: 'Pedra Branca do Amapari', label: 'Pedra Branca do Amapari'},
    {value: 'Porto Grande', label: 'Porto Grande'}, {value: 'Pracuúba', label: 'Pracuúba'}, {value: 'Santana', label: 'Santana'}, {value: 'Serra do Navio', label: 'Serra do Navio'}, {value: 'Tartarugalzinho', label: 'Tartarugalzinho'},
    {value: 'Vitória do Jari', label: 'Vitória do Jari'}
  ]},
  { value: 'BA', label: 'Bahia', cities: [ {value: 'Salvador', label: 'Salvador'}, {value: 'Feira de Santana', label: 'Feira de Santana'}, {value: 'Vitória da Conquista', label: 'Vitória da Conquista'}, {value: 'Camaçari', label: 'Camaçari'}, {value: 'Itabuna', label: 'Itabuna'}, {value: 'Juazeiro', label: 'Juazeiro'}, {value: 'Lauro de Freitas', label: 'Lauro de Freitas'}, {value: 'Ilhéus', label: 'Ilhéus'}, {value: 'Jequié', label: 'Jequié'}, {value: 'Teixeira de Freitas', label: 'Teixeira de Freitas'} ]},
  { value: 'CE', label: 'Ceará', cities: [ {value: 'Fortaleza', label: 'Fortaleza'}, {value: 'Caucaia', label: 'Caucaia'}, {value: 'Juazeiro do Norte', label: 'Juazeiro do Norte'}, {value: 'Maracanaú', label: 'Maracanaú'}, {value: 'Sobral', label: 'Sobral'} ]},
  { value: 'DF', label: 'Distrito Federal', cities: [{value: 'Brasília', label: 'Brasília'}] },
  { value: 'ES', label: 'Espírito Santo', cities: [ {value: 'Serra', label: 'Serra'}, {value: 'Vila Velha', label: 'Vila Velha'}, {value: 'Cariacica', label: 'Cariacica'}, {value: 'Vitória', label: 'Vitória'}, {value: 'Cachoeiro de Itapemirim', label: 'Cachoeiro de Itapemirim'} ]},
  { value: 'GO', label: 'Goiás', cities: [ {value: 'Goiânia', label: 'Goiânia'}, {value: 'Aparecida de Goiânia', label: 'Aparecida de Goiânia'}, {value: 'Anápolis', label: 'Anápolis'}, {value: 'Rio Verde', label: 'Rio Verde'}, {value: 'Luziânia', label: 'Luziânia'} ]},
  { value: 'MA', label: 'Maranhão', cities: [ {value: 'São Luís', label: 'São Luís'}, {value: 'Imperatriz', label: 'Imperatriz'}, {value: 'São José de Ribamar', label: 'São José de Ribamar'}, {value: 'Timon', label: 'Timon'}, {value: 'Caxias', label: 'Caxias'} ]},
  { value: 'MT', label: 'Mato Grosso', cities: [ {value: 'Cuiabá', label: 'Cuiabá'}, {value: 'Várzea Grande', label: 'Várzea Grande'}, {value: 'Rondonópolis', label: 'Rondonópolis'}, {value: 'Sinop', label: 'Sinop'}, {value: 'Tangará da Serra', label: 'Tangará da Serra'} ]},
  { value: 'MS', label: 'Mato Grosso do Sul', cities: [ {value: 'Campo Grande', label: 'Campo Grande'}, {value: 'Dourados', label: 'Dourados'}, {value: 'Três Lagoas', label: 'Três Lagoas'}, {value: 'Corumbá', label: 'Corumbá'}, {value: 'Ponta Porã', label: 'Ponta Porã'} ]},
  { value: 'MG', label: 'Minas Gerais', cities: [ {value: 'Belo Horizonte', label: 'Belo Horizonte'}, {value: 'Uberlândia', label: 'Uberlândia'}, {value: 'Contagem', label: 'Contagem'}, {value: 'Juiz de Fora', label: 'Juiz de Fora'}, {value: 'Betim', label: 'Betim'}, {value: 'Montes Claros', label: 'Montes Claros'}, {value: 'Ribeirão das Neves', label: 'Ribeirão das Neves'}, {value: 'Uberaba', label: 'Uberaba'}, {value: 'Governador Valadares', label: 'Governador Valadares'}, {value: 'Ipatinga', label: 'Ipatinga'} ]},
  { value: 'PA', label: 'Pará', cities: [ {value: 'Belém', label: 'Belém'}, {value: 'Ananindeua', label: 'Ananindeua'}, {value: 'Santarém', label: 'Santarém'}, {value: 'Marabá', label: 'Marabá'}, {value: 'Parauapebas', label: 'Parauapebas'} ]},
  { value: 'PB', label: 'Paraíba', cities: [ {value: 'João Pessoa', label: 'João Pessoa'}, {value: 'Campina Grande', label: 'Campina Grande'}, {value: 'Santa Rita', label: 'Santa Rita'}, {value: 'Patos', label: 'Patos'}, {value: 'Bayeux', label: 'Bayeux'} ]},
  { value: 'PR', label: 'Paraná', cities: [ {value: 'Curitiba', label: 'Curitiba'}, {value: 'Londrina', label: 'Londrina'}, {value: 'Maringá', label: 'Maringá'}, {value: 'Ponta Grossa', label: 'Ponta Grossa'}, {value: 'Cascavel', label: 'Cascavel'}, {value: 'São José dos Pinhais', label: 'São José dos Pinhais'}, {value: 'Foz do Iguaçu', label: 'Foz do Iguaçu'}, {value: 'Colombo', label: 'Colombo'}, {value: 'Guarapuava', label: 'Guarapuava'}, {value: 'Paranaguá', label: 'Paranaguá'} ]},
  { value: 'PE', label: 'Pernambuco', cities: [ {value: 'Recife', label: 'Recife'}, {value: 'Jaboatão dos Guararapes', label: 'Jaboatão dos Guararapes'}, {value: 'Olinda', label: 'Olinda'}, {value: 'Caruaru', label: 'Caruaru'}, {value: 'Paulista', label: 'Paulista'} ]},
  { value: 'PI', label: 'Piauí', cities: [ {value: 'Teresina', label: 'Teresina'}, {value: 'Parnaíba', label: 'Parnaíba'}, {value: 'Picos', label: 'Picos'}, {value: 'Piripiri', label: 'Piripiri'}, {value: 'Floriano', label: 'Floriano'} ]},
  { value: 'RJ', label: 'Rio de Janeiro', cities: [ {value: 'Rio de Janeiro', label: 'Rio de Janeiro'}, {value: 'São Gonçalo', label: 'São Gonçalo'}, {value: 'Duque de Caxias', label: 'Duque de Caxias'}, {value: 'Nova Iguaçu', label: 'Nova Iguaçu'}, {value: 'Niterói', label: 'Niterói'}, {value: 'Belford Roxo', label: 'Belford Roxo'}, {value: 'Campos dos Goytacazes', label: 'Campos dos Goytacazes'}, {value: 'São João de Meriti', label: 'São João de Meriti'}, {value: 'Petrópolis', label: 'Petrópolis'}, {value: 'Volta Redonda', label: 'Volta Redonda'} ]},
  { value: 'RN', label: 'Rio Grande do Norte', cities: [ {value: 'Natal', label: 'Natal'}, {value: 'Mossoró', label: 'Mossoró'}, {value: 'Parnamirim', label: 'Parnamirim'}, {value: 'São Gonçalo do Amarante', label: 'São Gonçalo do Amarante'}, {value: 'Macaíba', label: 'Macaíba'} ]},
  { value: 'RS', label: 'Rio Grande do Sul', cities: [ {value: 'Porto Alegre', label: 'Porto Alegre'}, {value: 'Caxias do Sul', label: 'Caxias do Sul'}, {value: 'Pelotas', label: 'Pelotas'}, {value: 'Canoas', label: 'Canoas'}, {value: 'Santa Maria', label: 'Santa Maria'}, {value: 'Gravataí', label: 'Gravataí'}, {value: 'Viamão', label: 'Viamão'}, {value: 'Novo Hamburgo', label: 'Novo Hamburgo'}, {value: 'São Leopoldo', label: 'São Leopoldo'}, {value: 'Rio Grande', label: 'Rio Grande'} ]},
  { value: 'RO', label: 'Rondônia', cities: [ {value: 'Porto Velho', label: 'Porto Velho'}, {value: 'Ji-Paraná', label: 'Ji-Paraná'}, {value: 'Ariquemes', label: 'Ariquemes'}, {value: 'Vilhena', label: 'Vilhena'}, {value: 'Cacoal', label: 'Cacoal'} ]},
  { value: 'RR', label: 'Roraima', cities: [ {value: 'Boa Vista', label: 'Boa Vista'}, {value: 'Rorainópolis', label: 'Rorainópolis'}, {value: 'Caracaraí', label: 'Caracaraí'} ]},
  { value: 'SC', label: 'Santa Catarina', cities: [ {value: 'Joinville', label: 'Joinville'}, {value: 'Florianópolis', label: 'Florianópolis'}, {value: 'Blumenau', label: 'Blumenau'}, {value: 'São José', label: 'São José'}, {value: 'Chapecó', label: 'Chapecó'}, {value: 'Itajaí', label: 'Itajaí'}, {value: 'Criciúma', label: 'Criciúma'}, {value: 'Jaraguá do Sul', label: 'Jaraguá do Sul'}, {value: 'Palhoça', label: 'Palhoça'}, {value: 'Lages', label: 'Lages'} ]},
  { value: 'SP', label: 'São Paulo', cities: [ {value: 'São Paulo', label: 'São Paulo'}, {value: 'Guarulhos', label: 'Guarulhos'}, {value: 'Campinas', label: 'Campinas'}, {value: 'São Bernardo do Campo', label: 'São Bernardo do Campo'}, {value: 'Santo André', label: 'Santo André'}, {value: 'Osasco', label: 'Osasco'}, {value: 'Sorocaba', label: 'Sorocaba'}, {value: 'Ribeirão Preto', label: 'Ribeirão Preto'}, {value: 'São José dos Campos', label: 'São José dos Campos'}, {value: 'Santos', label: 'Santos'}, {value: 'Valinhos', label: 'Valinhos'} ]},
  { value: 'SE', label: 'Sergipe', cities: [ {value: 'Aracaju', label: 'Aracaju'}, {value: 'Nossa Senhora do Socorro', label: 'Nossa Senhora do Socorro'}, {value: 'Lagarto', label: 'Lagarto'}, {value: 'Itabaiana', label: 'Itabaiana'}, {value: 'São Cristóvão', label: 'São Cristóvão'} ]},
  { value: 'TO', label: 'Tocantins', cities: [ {value: 'Palmas', label: 'Palmas'}, {value: 'Araguaína', label: 'Araguaína'}, {value: 'Gurupi', label: 'Gurupi'}, {value: 'Porto Nacional', label: 'Porto Nacional'}, {value: 'Paraíso do Tocantins', label: 'Paraíso do Tocantins'} ]},
].map(state => ({ ...state, cities: state.cities.sort((a,b) => a.label.localeCompare(b.label)) })).sort((a,b) => a.label.localeCompare(b.label));

export const BRAZILIAN_STATES_AND_CITIES = brazilianMunicipalities;


export const AUTOMOTIVE_REFERENCE_DATA = {
  vehicleBrands: [
    'Fiat', 'Volkswagen', 'Chevrolet', 'Ford', 'Renault', 'Hyundai', 'Toyota', 'Honda', 'Jeep', 'Nissan', 'Peugeot', 'Citroën', 'Mitsubishi', 'Mercedes-Benz', 'BMW', 'Audi', 'Kia', 'Chery', 'JAC',
    'Honda (Moto)', 'Yamaha', 'Suzuki', 'Kawasaki', 'Ducati', 'BMW (Moto)', 'Harley-Davidson', 'Triumph', 'KTM', 'Aprilia', 'Dafra', 'Traxx', 'Shineray', 'Kasinski',
    'Mercedes-Benz (Caminhão)', 'Volvo', 'Scania', 'MAN', 'Iveco', 'Ford (Caminhão)', 'Volkswagen (Caminhão)', 'DAF', 'Agrale', 'International',
    'Mercedes-Benz (Ônibus)', 'Volkswagen (Ônibus)', 'Scania (Ônibus)', 'Agrale (Ônibus)', 'Marcopolo (Ônibus)', 'Comil (Ônibus)', 'Neobus (Ônibus)', 'Busscar (Ônibus)',
    'Outra'
  ].sort((a,b) => a.localeCompare(b)),
  vehicleModels: {
    'Fiat': ['Uno', 'Palio', 'Siena', 'Strada', 'Toro', 'Mobi', 'Argo', 'Cronos', 'Pulse', 'Fastback', 'Doblo', 'Ducato', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Volkswagen': ['Gol', 'Fox', 'Voyage', 'Saveiro', 'Polo', 'Virtus', 'Nivus', 'T-Cross', 'Taos', 'Amarok', 'Tiguan', 'Jetta', 'Passat', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Chevrolet': ['Onix', 'Prisma', 'Cobalt', 'Spin', 'Tracker', 'S10', 'Montana', 'Cruze', 'Equinox', 'Camaro', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Ford': ['Ka', 'Fiesta', 'EcoSport', 'Focus', 'Ranger', 'Territory', 'Bronco Sport', 'Edge', 'Fusion', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Renault': ['Sandero', 'Logan', 'Kwid', 'Duster', 'Captur', 'Oroch', 'Fluence', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Hyundai': ['HB20', 'Creta', 'HB20S', 'Tucson', 'Elantra', 'Azera', 'Santa Fe', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Toyota': ['Corolla', 'Hilux', 'Yaris', 'Etios', 'Corolla Cross', 'SW4', 'RAV4', 'Camry', 'Prius', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Honda': ['Civic', 'Fit', 'City', 'HR-V', 'WR-V', 'CR-V', 'Accord', 'Pilot', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Jeep': ['Renegade', 'Compass', 'Commander', 'Wrangler', 'Grand Cherokee', 'Cherokee', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Nissan': ['March', 'Versa', 'Kicks', 'Sentra', 'Frontier', 'X-Trail', 'Altima', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Peugeot': ['208', '2008', '3008', '5008', '308', '408', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Citroën': ['C3', 'C4 Cactus', 'Aircross', 'C4 Lounge', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Mitsubishi': ['L200 Triton', 'Pajero', 'Eclipse Cross', 'Outlander', 'ASX', 'Lancer', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Mercedes-Benz': ['Classe A', 'Classe C', 'Classe E', 'GLA', 'GLC', 'GLE', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'BMW': ['Série 1', 'Série 3', 'Série 5', 'X1', 'X3', 'X5', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Audi': ['A3', 'A4', 'A6', 'Q3', 'Q5', 'Q7', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Kia': ['Picanto', 'Rio', 'Cerato', 'Sportage', 'Sorento', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Chery': ['QQ', 'Celer', 'Tiggo', 'Arrizo', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'JAC': ['J2', 'J3', 'J5', 'J6', 'T40', 'T50', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Honda (Moto)': ['CG 160', 'CB 600F', 'CBR 600RR', 'XRE 300', 'Biz 125', 'PCX 150', 'CB 1000R', 'Africa Twin', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Yamaha': ['YBR 125', 'Factor 150', 'XTZ 250', 'MT-07', 'MT-09', 'R1', 'R6', 'Tenere 700', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Suzuki': ['Intruder 125', 'GSX-R 1000', 'V-Strom 650', 'Bandit 650', 'GSX-S 750', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Kawasaki': ['Ninja 300', 'Ninja 650', 'Z900', 'Versys 650', 'ZX-10R', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Ducati': ['Monster 821', 'Panigale V4', 'Multistrada 1260', 'Scrambler', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'BMW (Moto)': ['G 310 R', 'F 850 GS', 'R 1250 GS', 'S 1000 RR', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Harley-Davidson': ['Iron 883', 'Street 750', 'Fat Boy', 'Road King', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Triumph': ['Street Triple', 'Tiger 800', 'Bonneville', 'Speed Triple', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'KTM': ['Duke 200', 'Duke 390', 'Adventure 1290', 'RC 390', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Aprilia': ['RS 660', 'Tuono V4', 'Shiver 900', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Dafra': ['Apache 150', 'Next 250', 'NH 190', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Traxx': ['JH 150', 'JL 50Q', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Shineray': ['XY 150', 'XY 200', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Kasinski': ['Comet 250', 'Mirage 150', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Mercedes-Benz (Caminhão)': ['Accelo', 'Atego', 'Axor', 'Actros', '1113', '1313', '1513', '1718', '2426', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Volvo': ['VM 210', 'VM 270', 'FH 400', 'FH 460', 'FH 540', 'FM 350', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Scania': ['P 250', 'P 320', 'R 440', 'R 500', 'S 500', 'G 420', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'MAN': ['TGX 28.440', 'TGX 29.480', 'TGS 24.280', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Iveco': ['Daily', 'Tector 170E22', 'Stralis 440', 'Hi-Way 600S44T', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Ford (Caminhão)': ['Cargo 816', 'Cargo 1119', 'Cargo 1722', 'Cargo 2428', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Volkswagen (Caminhão)': ['Delivery 6.160', 'Delivery 9.170', 'Constellation 17.280', 'Constellation 24.280', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'DAF': ['CF 85', 'XF 105', 'LF 45', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Agrale': ['8500', '10000', '14000', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'International': ['4300', '7400', '9800', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Mercedes-Benz (Ônibus)': ['O 500 RS', 'O 500 RSD', 'OF 1721', 'OF 1519', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Volkswagen (Ônibus)': ['17.230 EOD', '9.160 OD', '15.190 EOD', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Scania (Ônibus)': ['K 310', 'K 400', 'K 250', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Agrale (Ônibus)': ['MT 17.0', 'MA 8.5', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Marcopolo (Ônibus)': ['Paradiso 1200', 'Viaggio 1050', 'Torino', 'Senior', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Comil (Ônibus)': ['Campione 3.65', 'Svelto', 'Pia', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Neobus (Ônibus)': ['New Road', 'Spectrum', 'Mega BRT', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Busscar (Ônibus)': ['Vissta Buss', 'Urbanuss', 'Outro'].sort((a,b) => a.localeCompare(b)),
    'Outra': ['Outro Modelo']
  },
  vehicleYears: Array.from({length: 50}, (_, i) => (new Date().getFullYear() - i).toString()).sort((a,b) => b.localeCompare(a)),
  partNames: [
    'Alternador', 'Amortecedor', 'Air Bag',
    'Bandeja', 'Bateria', 'Bicos Injetores', 'Bloco do Motor', 'Bobina de Ignição', 'Bomba d\'Água', 'Bomba de Combustível', 'Bomba de Direção', 'Bancos Dianteiros', 'Banco Traseiro', 'Barra Estabilizadora', 'Borracha do Para-brisa', 'Bucha da Bandeja',
    'Cabeçote', 'Caixa de Direção', 'Calotas', 'Câmbio', 'Capô', 'Carroceria (Caminhão)', 'Cárter', 'Catalisador', 'Chave de Roda', 'Chicote Elétrico', 'Cilindro de Roda', 'Cilindro Mestre', 'Cintos de Segurança', 'Coletor de Escape', 'Coluna da Porta', 'Comando de Ar Condicionado', 'Compressor de Ar', 'Compressor do Ar', 'Condensador', 'Condensador do Ar', 'Console Central', 'Corpo de Borboleta (TBI)', 'Corrente', 'Coroa',
    'Diferencial', 'Disco de Freio',
    'Eixo Dianteiro', 'Eixo Traseiro', 'Embreagem', 'Escapamento (Moto)', 'Escapamento Completo', 'Estepe', 'Evaporador',
    'Farol de Milha', 'Farol Direito', 'Farol Esquerdo', 'Filtro de Combustível', 'Filtro do Ar Condicionado', 'Flauta de Combustível', 'Forro de Porta', 'Freio a Disco (Moto)', 'Freio Dianteiro', 'Freio Traseiro', 'Fusível',
    'Garfo Dianteiro', 'Guidão',
    'Hidrovácuo',
    'Lanterna Traseira Direita', 'Lanterna Traseira Esquerda', 'Luz de Freio', 'Luz de Ré', 'Luz Interna',
    'Macaco', 'Mangueira do Radiador', 'Módulo de Injeção (ECU)', 'Mola', 'Motor', 'Motor de Arranque',
    'Painel de Instrumentos', 'Para-brisa', 'Para-choque Dianteiro', 'Para-choque Traseiro', 'Para-lama Dianteiro Direito', 'Para-lama Dianteiro Esquerdo', 'Pastilha de Freio', 'Peças Específicas para Caminhões', 'Peças Específicas para Motos', 'Pinhão', 'Pistão', 'Pisca-pisca', 'Pivô', 'Pneus', 'Porta Dianteira Direita', 'Porta Dianteira Esquerda', 'Porta Traseira Direita', 'Porta Traseira Esquerda',
    'Quinta Roda',
    'Radiador', 'Rádio/Multimídia', 'Regulador de Pressão', 'Relé', 'Reservatório de Água', 'Reservatório de Ar', 'Retrovisor Direito', 'Retrovisor Esquerdo', 'Retrovisor Interno', 'Roda Dianteira (Moto)', 'Roda Traseira (Moto)', 'Rodas', 'Rolamento da Roda',
    'Sapata de Freio', 'Sensor de Rotação', 'Sensor de Temperatura', 'Servo Freio', 'Silencioso', 'Sistema de Arrefecimento', 'Sistema de Combustível', 'Sistema de Escape', 'Sistema de Freios', 'Sistema de Iluminação', 'Sistema Elétrico', 'Sistema Pneumático', 'Soleira da Porta', 'Sonda Lambda', 'Suspensão Dianteira', 'Suspensão Traseira', 'Suspensão Traseira (Moto)',
    'Tampa do Porta-malas', 'Tambor de Freio', 'Tanque de Combustível', 'Tanque de Combustível (Moto)', 'Tapete', 'Terminal de Direção', 'Termostato', 'Teto Solar', 'Tubo de Escape',
    'Válvula de Expansão', 'Válvula Pedal', 'Ventoinha', 'Vidro da Porta', 'Vidro Lateral', 'Vigia Traseiro', 'Virabrequim', 'Volante', 'Volante do Motor',
    'Outra Peça'
  ].sort((a,b) => a.localeCompare(b))
};
