export const SUBSCRIPTION_PLANS = [
  {
    code: 'local',
    name: 'Local',
    price: 47,
    reach: 'Até 20 km',
    priority: 'Recebe após 4 horas',
    accesses: '1 acesso simultâneo',
    description: 'Para atender perto da sua empresa.',
    features: ['Selo de empresa verificada', 'Fotos nas respostas', 'Página pública da empresa'],
  },
  {
    code: 'regional',
    name: 'Regional',
    price: 67,
    reach: 'Até 50 km',
    priority: 'Recebe após 3 horas',
    accesses: '1 acesso simultâneo',
    description: 'Mais cidades ao redor da sua operação.',
    features: ['Tudo do Local', 'Resposta destacada nas comparações'],
  },
  {
    code: 'multiregional',
    name: 'Multirregional',
    price: 97,
    reach: 'Até 100 km',
    priority: 'Recebe após 2 horas',
    accesses: '3 acessos simultâneos',
    description: 'Mais alcance e equipe para responder.',
    featured: true,
    features: ['Tudo do Regional', 'Relatório básico de desempenho'],
  },
  {
    code: 'estadual',
    name: 'Estadual',
    price: 147,
    reach: 'Todo o estado',
    priority: 'Recebe após 1 hora',
    accesses: 'Acessos ilimitados',
    description: 'Cobertura completa dentro do seu estado.',
    features: ['Tudo do Multirregional', 'Respostas fixadas no topo', 'Relatório completo'],
  },
  {
    code: 'nacional',
    name: 'Nacional',
    price: 297,
    reach: 'Brasil com seleção inteligente',
    priority: 'Recebe imediatamente',
    accesses: 'Acessos ilimitados',
    description: 'Oportunidades nacionais selecionadas para sua empresa.',
    features: ['Tudo do Estadual', 'Oportunidades nacionais', 'Selo para peças raras'],
  },
];

export const findSubscriptionPlan = (code) => SUBSCRIPTION_PLANS.find(plan => plan.code === code) || null;
