BEGIN;

CREATE TABLE IF NOT EXISTS public.ui_error_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text,
  message text NOT NULL,
  component_stack text,
  page_path text,
  user_agent text,
  app_version text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ui_error_events_created_at_idx
  ON public.ui_error_events (created_at DESC);

ALTER TABLE public.ui_error_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ui_error_events FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.log_ui_error(
  p_message text,
  p_component_stack text DEFAULT NULL,
  p_page_path text DEFAULT NULL,
  p_user_agent text DEFAULT NULL,
  p_app_version text DEFAULT NULL
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  INSERT INTO public.ui_error_events (
    user_id, message, component_stack, page_path, user_agent, app_version
  ) VALUES (
    auth.uid()::text,
    left(coalesce(nullif(trim(p_message), ''), 'Erro de interface sem mensagem'), 2000),
    left(p_component_stack, 12000),
    left(p_page_path, 1000),
    left(p_user_agent, 2000),
    left(p_app_version, 200)
  );
$$;

REVOKE ALL ON FUNCTION public.log_ui_error(text, text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.log_ui_error(text, text, text, text, text) TO anon, authenticated;

COMMIT;
