CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION public.normalize_catalog_text(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT trim(
    regexp_replace(
      translate(
        lower(coalesce(p_value, '')),
        'áàâãäéèêëíìîïóòôõöúùûüçñ',
        'aaaaaeeeeiiiiooooouuuucn'
      ),
      '[^a-z0-9]+',
      ' ',
      'g'
    )
  );
$$;

CREATE TABLE IF NOT EXISTS public.part_catalog (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  source_id text NOT NULL,
  name text NOT NULL,
  normalized_name text NOT NULL,
  category_name text,
  category_path text[] NOT NULL DEFAULT '{}',
  aliases text[] NOT NULL DEFAULT '{}',
  vehicle_types text[] NOT NULL DEFAULT ARRAY['car']::text[],
  is_high_value boolean NOT NULL DEFAULT false,
  is_searchable boolean NOT NULL DEFAULT true,
  active boolean NOT NULL DEFAULT true,
  source_updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT part_catalog_source_id_unique UNIQUE (source, source_id),
  CONSTRAINT part_catalog_name_not_blank CHECK (length(trim(name)) > 0),
  CONSTRAINT part_catalog_vehicle_types_valid CHECK (
    vehicle_types <@ ARRAY['car', 'motorcycle', 'truck', 'bus']::text[]
    AND cardinality(vehicle_types) > 0
  )
);

CREATE INDEX IF NOT EXISTS part_catalog_name_trgm_idx
  ON public.part_catalog USING gin (normalized_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS part_catalog_aliases_idx
  ON public.part_catalog USING gin (aliases);
CREATE INDEX IF NOT EXISTS part_catalog_vehicle_types_idx
  ON public.part_catalog USING gin (vehicle_types);
CREATE INDEX IF NOT EXISTS part_catalog_active_searchable_idx
  ON public.part_catalog (active, is_searchable, name);

ALTER TABLE public.part_catalog ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS part_catalog_public_read ON public.part_catalog;
CREATE POLICY part_catalog_public_read
  ON public.part_catalog
  FOR SELECT
  TO anon, authenticated
  USING (active AND is_searchable);

GRANT SELECT ON public.part_catalog TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.part_catalog_syncs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  source_created_at timestamptz,
  records_seen integer NOT NULL DEFAULT 0,
  records_imported integer NOT NULL DEFAULT 0,
  searchable_records integer NOT NULL DEFAULT 0,
  synced_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.part_catalog_syncs ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.search_part_catalog(
  p_query text DEFAULT '',
  p_vehicle_type text DEFAULT NULL,
  p_limit integer DEFAULT 80
)
RETURNS TABLE (
  id bigint,
  name text,
  aliases text[],
  category_name text,
  category_path text[],
  vehicle_types text[],
  is_high_value boolean
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH prepared AS (
    SELECT public.normalize_catalog_text(p_query) AS query
  )
  SELECT
    catalog.id,
    catalog.name,
    catalog.aliases,
    catalog.category_name,
    catalog.category_path,
    catalog.vehicle_types,
    catalog.is_high_value
  FROM public.part_catalog AS catalog
  CROSS JOIN prepared
  WHERE catalog.active
    AND catalog.is_searchable
    AND (
      p_vehicle_type IS NULL
      OR p_vehicle_type = ANY(catalog.vehicle_types)
    )
    AND (
      prepared.query = ''
      OR catalog.normalized_name LIKE '%' || prepared.query || '%'
      OR public.normalize_catalog_text(array_to_string(catalog.aliases, ' ')) LIKE '%' || prepared.query || '%'
      OR catalog.normalized_name % prepared.query
    )
  ORDER BY
    CASE
      WHEN catalog.normalized_name = prepared.query THEN 0
      WHEN catalog.normalized_name LIKE prepared.query || '%' THEN 1
      WHEN catalog.normalized_name LIKE '%' || prepared.query || '%' THEN 2
      ELSE 3
    END,
    similarity(catalog.normalized_name, prepared.query) DESC,
    catalog.name
  LIMIT LEAST(GREATEST(coalesce(p_limit, 80), 1), 200);
$$;

GRANT EXECUTE ON FUNCTION public.search_part_catalog(text, text, integer) TO anon, authenticated;
